gif:
  mediaDirectoryPath: ${GIF_DIRECTORY:stored_gifs}

quarkus:
  http:
    limits:
      max-body-size: 500M
  rest-client:
    chroma-rest-client:
      url: ${CHROMA_URL:http://localhost:15432}
  datasource:
    devservices:
      enabled: false
      port: 5432
      username: postgres
      password: postgres
      db-name: dj-khaled-reactionator
      volumes:
        dev-data-volume: /var/lib/postgresql/data
    db-kind: postgresql
    username: ${POSTGRESQL_USERNAME:postgres}
    password: ${POSTGRESQL_PASSWORD:postgres}
    jdbc:
      url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DB:dj-khaled-reactionator}
    log:
      sql: true

  langchain4j:
    openai:
      api-key: ${OPENAI_API_KEY:key}
      embedding-model:
        model-name: text-embedding-3-small
    chroma:
      devservices:
        enabled: false
      url: ${CHROMA_URL:http://localhost:15432}
      collection-name: dj-khaled-reactionator-collection

  hibernate-orm:
    database:
      generation: validate

  liquibase:
    migrate-at-start: true
    change-log: db/changelog.xml