version: '3.8'

services:
  chromadb-ui:
    image: fengzhichao/chromadb-admin
    ports:
      - "3000:3000"
  chromadb:
    image: ghcr.io/chroma-core/chroma:0.4.15
    container_name: chromadb
    restart: unless-stopped
    ports:
      - "15432:8000"
    volumes:
      - ./chroma-data:/data
  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dj-khaled-reactionator